### 로그인

POST http://localhost:9000/auth/login
Content-Type: application/json

{
   "email": "ybchar@test.com",
   "password": "qwer1234"
}

### 세션 테스트
GET http://localhost:9000/posts/authTest
Content-Type: application/json
Cookie: SESSION:1624148c-de06-4643-bf6e-e3ea2bb2ba9c